# Exercise Notebook (DS)

In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

In [2]:
elements = [3,5,6,8,2,9]
print(type(elements))
print(elements)

<class 'list'>
[3, 5, 6, 8, 2, 9]


In [3]:
elements = np.array(elements)
print(type(elements))
print(elements)

<class 'numpy.ndarray'>
[3 5 6 8 2 9]


#### NumPy - Array Attributes

`ndarray.shape`
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

**Examples**

In [4]:
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
a

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# this resizes the ndarray 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)

[[1 2]
 [3 4]
 [5 6]]


NumPy also provides a reshape function to resize an array.

In [6]:
a = np.array([[1,2,5],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

[[1 2]
 [5 4]
 [5 6]]


#### ndarray.ndim
This array attribute returns the number of array dimensions.

`Example`

In [7]:
elements.ndim

1

In [8]:
# an array of evenly spaced numbers 
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
# this is one dimensional array 
a = np.arange(24) 
print(a.ndim)  

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions
print(b.ndim)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [10]:
b[1][1][2]

17

In [11]:
# array of five zeros. Default dtype is float 
x = np.zeros(5) 
print (x)

[0. 0. 0. 0. 0.]


In [12]:
# array of five ones. Default dtype is float  
x = np.ones(5) 
print (x)

[1. 1. 1. 1. 1.]


#### NumPy - Array From Existing Data

**numpy.asarray**
This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

In [13]:
# convert list to ndarray 

x = [1,2,3]
a = np.asarray(x) 
print (a)

[1 2 3]


In [14]:
# ndarray from list of tuples 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


D:\Anaconda\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


#### numpy.frombuffer
This function interprets a buffer as one-dimensional array. Any object that exposes the buffer interface is used as parameter to return an ndarray.

`numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)`

##### The constructor takes the following parameters.

Sr.No.	Parameter & Description
1. buffer

Any object that exposes buffer interface

2. dtype

Data type of returned ndarray. Defaults to float

3. count

The number of items to read, default -1 means all data

4. offset

The starting position to read from. Default is 0

#### Operations on Numpy Array

In [15]:
# 2D Numpy Array
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [16]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [17]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [18]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [19]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

**NumPy - Indexing & Slicing**

Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving **start, stop, and step** parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [20]:
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [21]:
a = np.arange(10) 
print(a)
b = a[2:7:2] 
print (b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [22]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a ) 

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


#### Numpy 2D Array

In [23]:
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [24]:
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [25]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [26]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [27]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [65]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

##### Task

In [28]:
import numpy as np
arr = np.array([1,1,np.nan,np.nan,0,0])
print(np.isnan(arr))

[False False  True  True False False]


2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [35]:
import numpy as np
arr = np.array([1,1+0j,np.nan,np.nan,10+9j,0])

#Check for complex number
print(np.iscomplex(arr))

#Check for real number
print(np.isreal(arr))

#Check for scalar type
print(np.isscalar(arr))
#type(arr) --> numpy.ndarray

[False False False False  True False]
[ True  True  True  True False  True]
False
