# Exercise Notebook (DS)

In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

#### Calculating BMI

In [2]:
# Base Ball Player's Heights AS a
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [3]:
# Base Ball Player's Weight AS b
b = np.array([5,7,10]) 
print (b)

[ 5  7 10]


Body Mass Index (BMI) is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg is a person's weight in kilograms and m2 is their height in metres squared.

In [4]:
bmi = (b/(a**2))
bmi

array([5.        , 1.75      , 1.11111111])

In [5]:
lightweight_baseball_players = bmi < (max(bmi)-min(bmi))
lightweight_baseball_players

array([False,  True,  True])

In [6]:
# more than one dimensions 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [7]:
# minimum dimensions 
a = np.array([1, 2, 8,3,4,5], ndmin = 1) 
print (a)

[1 2 8 3 4 5]


**Task**

1. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [9]:
import numpy as np

arr = np.array([1, np.nan, 1, 0, np.inf])
print(np.isfinite(arr))

[ True False  True  True False]


2. Write a NumPy program to test element-wise for positive or negative infinity.

In [10]:
import numpy as np

arr = np.array([1, np.nan, 1, 0, np.inf])
print(np.isinf(arr))

[False False False False  True]
